-- MySQL Script generated by MySQL Workbench
-- Mon Oct  7 22:17:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EjemploInstituto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EjemploInstituto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EjemploInstituto` DEFAULT CHARACTER SET utf8 ;
USE `EjemploInstituto` ;

-- -----------------------------------------------------
-- Table `EjemploInstituto`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EjemploInstituto`.`alumnos` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `DNI` INT NOT NULL,
  `Fecha_de_nacimiento` DATE NULL,
  PRIMARY KEY (`id_alumno`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EjemploInstituto`.`Profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EjemploInstituto`.`Profesores` (
  `id_Profesor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `DNI` INT NOT NULL,
  PRIMARY KEY (`id_Profesor`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EjemploInstituto`.`Materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EjemploInstituto`.`Materias` (
  `id_Materia` INT NOT NULL AUTO_INCREMENT,
  `Nombre_materia` VARCHAR(45) NOT NULL,
  `id_Profesor` INT NOT NULL,
  PRIMARY KEY (`id_Materia`),
  INDEX `FK1_Profesor_idx` (`id_Profesor` ASC) VISIBLE,
  CONSTRAINT `FK1_Profesor`
    FOREIGN KEY (`id_Profesor`)
    REFERENCES `EjemploInstituto`.`Profesores` (`id_Profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EjemploInstituto`.`Inscripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EjemploInstituto`.`Inscripciones` (
  `id_Inscripciones` INT NOT NULL AUTO_INCREMENT,
  `id_alumno` INT NOT NULL,
  `id_materia` INT NOT NULL,
  `fecha_de_inscripcion` DATE NOT NULL,
  PRIMARY KEY (`id_Inscripciones`),
  INDEX `FK1_alumno_idx` (`id_alumno` ASC) VISIBLE,
  INDEX `FK2_materia_idx` (`id_materia` ASC) VISIBLE,
  CONSTRAINT `FK1_alumno`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `EjemploInstituto`.`alumnos` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK2_materia`
    FOREIGN KEY (`id_materia`)
    REFERENCES `EjemploInstituto`.`Materias` (`id_Materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
